name: Generate ReaPack index

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ruby dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev
          gem install bundler
          gem install rake

      - name: Download reapack-index
        run: |
          curl -L https://raw.githubusercontent.com/cfillion/reapack-index/master/bin/reapack-index -o reapack-index
          chmod +x reapack-index

      - name: Generate index.xml
        run: ruby reapack-index --generate index.xml .

      - name: Commit and push index.xml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.xml
          git commit -m "Auto-generate index.xml" || echo "No changes"
          git push
