name: Generate ReaPack index.xml

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install reapack-index gem
      run: gem install reapack-index

    - name: Generate index.xml
      run: reapack-index -i Scripts -o index.xml

    - name: Commit and push changes if index.xml changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add index.xml
        if ! git diff --cached --quiet; then
          git commit -m "Auto-update index.xml [skip ci]"
          git push
        else
          echo "No changes in index.xml"
        fi
